[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.7.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/juju/ratelimit"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[prune]
  go-tests = true
  unused-packages = true
